// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR1W5IWUdpeWLAkoi5rsTin4HFzXoUUlM',
    appId: '1:129491282884:web:99ab08ec9c2186823cd291',
    messagingSenderId: '129491282884',
    projectId: 'learn-flutter-67-019',
    authDomain: 'learn-flutter-67-019.firebaseapp.com',
    storageBucket: 'learn-flutter-67-019.firebasestorage.app',
    measurementId: 'G-2P1139L2JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0MXH_3Emcr3RJPZwxyJ_QkyVokSqYVns',
    appId: '1:129491282884:android:646f5419416d9e0f3cd291',
    messagingSenderId: '129491282884',
    projectId: 'learn-flutter-67-019',
    storageBucket: 'learn-flutter-67-019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtsolcZ0BT7pPyOtbQJSi9TW3EDnF6njE',
    appId: '1:129491282884:ios:ed0627a2705bc6df3cd291',
    messagingSenderId: '129491282884',
    projectId: 'learn-flutter-67-019',
    storageBucket: 'learn-flutter-67-019.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6712',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtsolcZ0BT7pPyOtbQJSi9TW3EDnF6njE',
    appId: '1:129491282884:ios:ed0627a2705bc6df3cd291',
    messagingSenderId: '129491282884',
    projectId: 'learn-flutter-67-019',
    storageBucket: 'learn-flutter-67-019.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6712',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR1W5IWUdpeWLAkoi5rsTin4HFzXoUUlM',
    appId: '1:129491282884:web:6840b5605ace49e93cd291',
    messagingSenderId: '129491282884',
    projectId: 'learn-flutter-67-019',
    authDomain: 'learn-flutter-67-019.firebaseapp.com',
    storageBucket: 'learn-flutter-67-019.firebasestorage.app',
    measurementId: 'G-MZ23T6XWZ1',
  );
}
